BlogWebsite/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.DB.Entities;
using Blog.DB.Interfaces;
using BlogWebsite.Respository;

namespace BlogWebsite.Controllers
{
    public class BlogController : Controller
    {
        IDatabaseRepository _dbRepo;
        public BlogController(IDatabaseRepository dbRepository)
        {
            _dbRepo = dbRepository;
        }

        // GET: Blog
        public ActionResult Index()
        {
            var articles = _dbRepo.GetAllArticles();
            return View("Index", articles);
        }
        [Authorize(Roles ="Admin, Editor")]
        public ActionResult Create()
        {

            return View();

        }
        [HttpPost]
        [Authorize(Roles = "Admin, Editor")]
        public ActionResult Create(Article article)
        {

            _dbRepo.CreateArticle(article);
            return RedirectToAction("Index");

        }
        [Authorize(Roles = "Admin, Editor")]

        public ActionResult Update(int id)
        {
            var article = _dbRepo.GetArticleById(id);
            return View(article);

        }
        [HttpPost]
        [Authorize(Roles = "Admin, Editor")]
        public ActionResult Update(Article article)
        {
            _dbRepo.UpdateArticle(article);
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin, Editor")]
        public ActionResult Delete(int id)
        {
            var article = _dbRepo.GetArticleById(id);
            return View(article);
        }
        [HttpPost]
        [Authorize(Roles = "Admin, Editor")]
        public ActionResult Delete(Article article)
        {

            _dbRepo.DeleteArticle(article);
            return RedirectToAction("Index");

        }
        public ActionResult Details(int id)
        {
            var article = _dbRepo.GetArticleById(id);
            return View(article);
        }

        [HttpPost]
        public ActionResult UploadImage()
        {
            JsonResult result = new JsonResult();
            var Images = Request.Files;
            for (var i = 0; i < Images.Count; i++)
            {
                var filename = Guid.NewGuid() + Path.GetExtension(Images[i].FileName);
                var path = Server.MapPath("~/Content/Images/") + filename;
                Images[i].SaveAs(path);
                result.Data = (filename);

            }
            
            return result;
        }
    }
}

BlogWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="../../Content/bootstrap.css" rel="stylesheet">
    <link href="../../Content/site.css" rel="stylesheet">
    <script src="../../Scripts/bootstrap.js"></script>
    <script src="../../Scripts/jquery-3.4.1.js"></script>
    <script src="../../Scripts/modernizr-2.8.3.js"></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Blogs", "Index", "Blog")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.Sitecore().Placeholder("main")
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


</body>
</html>